### ISSUE TITLE
Blury texture when using custom model in resourcepack (especially with size of not 16)

### ISSUE THREAD

**Issue by barraIhsan** [Chocohead/OptiFabric#144]
So i made a custom model (the size is like 5.3). But the textures is look so blurry
![image](https://user-images.githubusercontent.com/57800056/104093303-56e35380-52bc-11eb-97a6-e4b5388e04ae.png)
This is the actual file :
![image](https://user-images.githubusercontent.com/57800056/104093316-66fb3300-52bc-11eb-9c4e-10e3823bf035.png)

**Comment by Chocohead** [comment]
This is something OptiFine does. When you have a non-power-of-2 sized texture in vanilla it disables mipmapping, whilst OptiFine and Forge both scale the texture up to a power-of-2 to retain the mipmapping on it. Because of this though the resulting texture will be blured as it gets scaled back again in game.

There's a bit more about it here: sp614x/Optifine#1982
