### ISSUE TITLE
Can open 1.16.5 optifine ver. but cannot open as optifabric ver.

### ISSUE THREAD

**Issue by CamillaLee** [Chocohead/OptiFabric#168]
I have OptiFine_1.16.5_HD_U_G7(MODfile), installed fabric-api-0.30.3+1.16, and also have optifabric-1.9.2.jar in my mod folder

I can run 1.16.5 optifine ver. but everytime when I try to open with optifabric the error message pops up which says

'There was an error loading OptiFabric! this version of optifine is not compatible with the current minecraft version. the optifine requires 1.16.1, you have 1.16.5'

I don't understand what is wrong...

**Comment by USBCharger** [comment]
I'm getting the exact same error, but instead it's talking about 1.16.4 instead of 1.16.1, and when I give it 1.16.4 it gives me this error: https://imgur.com/a/MOGJn26|
My logs: https://pastebin.com/JwRdcmtn
Tried using 1.16.4 fabric, 1.16.5 fabric, 1.16.4 optifine, 1.16.5 optifine, failure after failure after failure. Would really like some help as due to wanting to use the replay mod and it being fabric only I'm stuck to fabric for the time being

**Comment by SamOnFabric** [comment]
same problem, tried to log in on 1.16.4 with optifabric and optifine for 1.16.4 and it tells me i need 1.15.2???
would like to know what i'm doing wrong

**Comment by Chocohead** [comment]
I've improved the error screen with the newest OptiFabric version which should help you work out what you need to fix
