### ISSUE TITLE
Incompatible with Optifine when you use fabric api 0.12.1

### ISSUE THREAD

**Issue by DEMEMZEA** [Chocohead/OptiFabric#394]
That's all

**Comment by TaintedPlaces** [comment]
Seconded. Please prioritize. Thank you!

**Comment by koitsu** [comment]
For those who want a workaround until the next version of OptiFabric is out:

* Open up optifabric-1.11.20.jar with WinRAR (or something else that can open/read/modify JAR files)
* In the JAR: find the file called `fabric.mod.json` and extract it to somewhere (like your desktop)
* Open the JSON file in a text editor (Notepad, Sublime, etc.)
* Find the section called `"depends"`, which will have a key called `"fabricloader"` -- it's around line 34
* Change the value from `">=0.8.0 <0.12"` to `">=0.8.0 <0.12.2"` (i.e. change `0.12` to `0.12.2`)
* Save the file
* Put the modified `fabric.mod.json` back into the JAR (replacing the existing one), and save the JAR

I'm not going to describe each step in further minute detail because it's too tedious.  I'm only providing the above because it allowed me to get things working again and I knew generally what I was doing.

**Comment by TaintedPlaces** [comment]
> For those who want a workaround until the next version of OptiFabric is out:
> 
> * Open up optifabric-1.11.20.jar with WinRAR (or something else that can open/read/modify JAR files)
> * In the JAR: find the file called `fabric.mod.json` and extract it to somewhere (like your desktop)
> * Open the JSON file in a text editor (Notepad, Sublime, etc.)
> * Find the section called `"depends"`, which will have a key called `"fabricloader"` -- it's around line 34
> * Change the value from `">=0.8.0 <0.12"` to `">=0.8.0 <0.12.2"` (i.e. change `0.12` to `0.12.2`)
> * Save the file
> * Put the modified `fabric.mod.json` back into the JAR (replacing the existing one), and save the JAR
> 
> I'm not going to describe each step in further minute detail because it's too tedious. I'm only providing the above because it allowed me to get things working again and I knew generally what I was doing.

Unfortunately, this did not work for me. I still receive an error message even though it's supposed to work in 1.12.2.

**Comment by Zerphim** [comment]
> That's all

hi Try using Optifabric 1.11.20 and OptiFine_1.17.1_HD_U_G9 instead of the H1 preview.

**Comment by kann101** [comment]
> > That's all
> 
> hi Try using Optifabric 1.11.20 and OptiFine_1.17.1_HD_U_G9 instead of the H1 preview.

I tested them but don’t work.

**Comment by Eiion** [comment]
> hi Try using Optifabric 1.11.20 and OptiFine_1.17.1_HD_U_G9 instead of the H1 preview.

Going with version OptiFine 1.17.1 HD U G9 instead of version OptiFine 1.17.1 HD U H1 fixed it for me. Thanks.

**Comment by taznotfound** [comment]
yeah for me its this code "\u003e\u003d0.8.0"
