### ISSUE TITLE
Not Compatible with Fabric Loader over 0.12.0

### ISSUE THREAD

**Issue by camerica7400** [Chocohead/OptiFabric#428]
Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
     Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from

**Comment by alien-sunset** [comment]
I am getting the same error

**Comment by elboletaire** [comment]
Same here

**Comment by illegitimate-egg** [comment]
The easiest solution is to modify the loading file for OptiFabric so that's it's compatible with all versions.

**Comment by QuJoD** [comment]
How would I acomplish that?

**Comment by Andariel78** [comment]
Same here. Please fix :)

**Comment by illegitimate-egg** [comment]
> How would I acomplish that?

You'd open the jar file, open the `fabric.mod.json` file and make these changes:
```
-34   "fabricloader": ">=0.8.0 <0.12",
+34   "fabricloader": ">=0.8.0 <0.13",
```
After these changes the mod will load. but there's still no chance that it'll detect modern versions of OptiFine.

**Comment by MysticMia** [comment]
~~This fabricloader limit redefining helped. I may not be able to use optifine, but it did help fix compatibility with another mod. Appleskin needed Fabric 0.12 but this mod didn't support it yet (at least, it said it didn't), but @cameronPeckDev 's fix helped.~~
Nevermind; it may have started but probably because of Fabric >0.11.7, it doesn't start up at all. It just doesn't give an error either. This means optifine doesn't work (yet) either

**Comment by ZekerZhayard** [comment]
same as https://github.com/Chocohead/OptiFabric/issues/394
