### ISSUE TITLE
1.19 crash on startup

### ISSUE THREAD

**Issue by peterjolly** [Chocohead/OptiFabric#822]
As stated, after I click Play, it crashes and says "This crash may be caused by an invalid Java Runtime configuration. Check and custom configuration settings. Exit Code: 1" I have everything updated as far as I know. I'll attach the latest log
[latest.log](https://github.com/Chocohead/OptiFabric/files/9274226/latest.log)
.

**Comment by jtljrdn** [comment]
After reviewing your logs, it doesn't seem like the issue is caused by OptiFabric, unless some mod is conflicting with it, but after looking at the modlist I don't think there is. It's almost definitely caused by some other mod so I would recommend going through and removing each mod one by one until you can figure out the problem. Tedious, I know, but I can't really tell based on the logs exactly what would be causing it.

Also, make sure you have the correct version of optifine installed for 1.19.

**Comment by peterjolly** [comment]
Weird, I tried that already but nothing seemed to cause it. Guess I'll give it another shot. Thanks!

**Comment by topia** [comment]
incompatible with inventorysorter: https://github.com/Chocohead/OptiFabric/issues/800#issuecomment-1193835896

**Comment by peterjolly** [comment]
I tried removing but it still does not boot up.
[latest.log](https://github.com/Chocohead/OptiFabric/files/9275479/latest.log)

**Comment by topia** [comment]
Now I think you encountered a very common problem on this repository, https://github.com/Chocohead/OptiFabric/issues/814; optifabric currently isn't compatible with H9 versions. Unfortunately, the developer doesn't seem to have enough time to resolve it.

**Comment by peterjolly** [comment]
That fixed it! It even works with the inventory mod I deleted before. Thanks a ton!
