### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by Mickamikaze** [Chocohead/OptiFabric#980]
Hello Modders,

i'm having an issue with Optifabric.

the connected textures don't work properly.

I'll add some pictures to sho. 

it depens on what orientation the glass is but on one side the connecting texture are ok, but at the other side, not...

anyone having this issue? I've Tried on a non fabric version, juste a Optinfine version and it works perfect on this one.

1.19.3, fabric loader & api are up to date.
![Minecraft Screenshot 2023 03 02 - 13 08 17 74](https://user-images.githubusercontent.com/126188974/222424691-24dfddf6-98ef-4a68-badc-db599b807af7.png)
![Minecraft Screenshot 2023 03 02 - 13 08 11 93](https://user-images.githubusercontent.com/126188974/222424699-4f196b24-6c44-46e6-b4a8-87320dca5fdb.png)

**Comment by stellacutie** [comment]
That's my issue too the connected glass pane texture don't connect correctly

**Comment by RU-B0** [comment]
yea its weird. It only happens when looking in the south and east directions, otherones being fine
looking south:
![2023-08-13_20 05 48](https://github.com/Chocohead/OptiFabric/assets/102103056/0818c0c0-6a94-4532-b077-52fe7724dd95)
East:
![2023-08-13_20 05 51](https://github.com/Chocohead/OptiFabric/assets/102103056/442aa927-96be-4807-82e1-3c0ae4014dc4)
North:
![2023-08-13_20 05 54](https://github.com/Chocohead/OptiFabric/assets/102103056/dac52fa6-cd4f-46d2-b488-e30721c5eba3)
West
![2023-08-13_20 05 57](https://github.com/Chocohead/OptiFabric/assets/102103056/03f81772-ccc1-458a-84a2-6c548ab04b58)
Idk but its really annoying.

**Comment by RU-B0** [comment]
Just wanted to comment how I fixed this issue: I found out that a mod called fusion (https://modrinth.com/mod/fusion-connected-textures) launches with OptiFine just fine. Using Midnighttigger's Default Connected Textures (https://modrinth.com/resourcepack/mt-ct-d/version/tfKvt8nl) and putting it as lowest priority on the resource pack list (but not below MC itself or fabric), it gets rid of this issue. Plus, OptiFine's implementation still works for other resource packs. Its a win - win. 

Tested with Fusion 1.0.5a and Optifine HD U I5, Optifabric 1.13.25, and FAPI 0.83.1 (+10000000000 other mods but you get the point)
